export const monthlyList = [
  {
    list_name: "Audio Fiction",
    display_name: "Audio Fiction",
    list_name_encoded: "audio-fiction",
    oldest_published_date: "2018-03-11",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
  {
    list_name: "Audio Nonfiction",
    display_name: "Audio Nonfiction",
    list_name_encoded: "audio-nonfiction",
    oldest_published_date: "2018-03-11",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
  {
    list_name: "Business Books",
    display_name: "Business",
    list_name_encoded: "business-books",
    oldest_published_date: "2013-11-03",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
  {
    list_name: "Graphic Books and Manga",
    display_name: "Graphic Books and Manga",
    list_name_encoded: "graphic-books-and-manga",
    oldest_published_date: "2019-10-13",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
  {
    list_name: "Mass Market Monthly",
    display_name: "Mass Market",
    list_name_encoded: "mass-market-monthly",
    oldest_published_date: "2019-10-13",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
  {
    list_name: "Middle Grade Paperback Monthly",
    display_name: "Middle Grade Paperback",
    list_name_encoded: "middle-grade-paperback-monthly",
    oldest_published_date: "2019-10-13",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
  {
    list_name: "Young Adult Paperback Monthly",
    display_name: "Young Adult Paperback",
    list_name_encoded: "young-adult-paperback-monthly",
    oldest_published_date: "2019-10-13",
    newest_published_date: "2023-07-16",
    updated: "MONTHLY",
  },
];
